### ISSUE TITLE
Is ASOCA allowed to be used in your articles

### ISSUE THREAD

**Issue by ChenFeiL** [qiyaolei/Examinee-Examiner-Network#1]

**Comment by qiyaolei** [comment]
Dear ChenFeiL,


I feel sorry for not replying to your email in time.


There may be two reasons but I am not sure.&nbsp;


1) Cite the relevant articles of the ASOCA organizers.
（[1] Gharleghi R, Adikari D, Ellenberger K, et al. Automated Segmentation of Normal and Diseased Coronary Arteries - The ASOCA Challenge[J]. Computerized Medical Imaging and Graphics, 2022: 102049.）


2）We entered the competition and were in the top 8. We are also on their list of co-authors, maybe this is one reason.


Finally, thank you very much for sending me this email. I am also committed to the related issues of coronary artery. I hope to have more exchanges with you in the future.


Sincerely,


&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Yaolei Qi
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qiyaolei/Examinee-Examiner-Network"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月22日(星期二) 中午12:13
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[qiyaolei/Examinee-Examiner-Network] Is ASOCA allowed to be used in your articles (Issue #1)





 
Dear author,
 
Is ASOCA dataset allowed to be used in your articles? Our article was retracted after using ASOCA.
